[package]
name = "steel_client"
version = "0.1.0"
authors = ["mattwparas <matthewparas2020@u.northwestern.edu>"]
edition = "2018"
license = "MIT OR Apache-2.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustyline = "5.0.6"
steel = { path = "./steel" }
steel_derive = { path = "./steel_derive"}

[workspace]
members = [
    "steel",
    "steel_derive",
]