[package]
name = "steel-gen"
version = "0.2.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
codegen = "0.2.0"
serde = { version = "1.0.152", features = ["derive"] }
serde_derive = "1.0.152"
itertools = "0.10.5"
