[package]
name = "steel-core"
# version = "0.4.0"
version.workspace = true
authors = ["mattwparas <matthewparas2020@u.northwestern.edu>"]
edition = "2021"
license = "MIT OR Apache-2.0"
repository = "https://github.com/mattwparas/steel"
description = "Core compiler and VM implementation for steel"


[lib]
name = "steel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
im-rc = "15.1.0"
codespan-reporting = "0.11.1"
log = "0.4.17"

futures-util = "0.3.28"
futures-task = "0.3.28"

serde_json = "1.0.108"
serde = { version = "1.0.193", features = ["derive", "rc"] }
serde_derive = "1.0.193"
bincode = "1.3.3"
pretty = "0.12.1"
im-lists = "0.8.0"
strsim = "0.11.0"
quickscope = "0.2.0"
lasso = { version = "0.7.2", features = ["multi-threaded", "serialize"] }
once_cell = "1.18.0"
fxhash = "0.2.1"
steel-gen = { path = "../steel-gen", version = "0.2.0" }
steel-parser = { path = "../steel-parser", version = "0.6.0" }
steel-derive = { path = "../steel-derive", version = "0.5.0" }
chrono = { version = "0.4.23", default-features = false, features = ["std", "clock"] }
weak-table = "0.3.2"
# TODO: Consider whether rand needs to be here
rand = "0.8.5"
# TODO: Consider only depending on the sub crate
num = "0.4.0"
radix_fmt = "1.0.0"

# For structs
smallvec = { version = "1.10.0" }

# Pretty printing documentation
termimad = { version = "0.21.0", optional = true }

# FFI for dylibs
abi_stable = { version = "0.11.2", optional = true }
async-ffi = { version = "0.5.0", features = ["abi_stable"], optional = true }
# Cranelift JIT
cranelift = { version = "0.84.0", optional = true }
cranelift-module = { version = "0.84.0", optional = true }
cranelift-jit = { version = "0.84.0", optional = true }

# Embedded dependencies for various popular libraries
rusqlite =  { version = "0.28.0", features = ["bundled"], optional = true }
reqwest = { version = "0.11.14", features = ["blocking", "json"], optional = true }
url = { version = "2.3.1", optional = true }
anyhow = { version = "1", optional = true }

stacker = { version = "0.1.15", optional = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
which = { version = "4.4.0" }

[dev-dependencies]
proptest = "1.1.0"
criterion = "0.5.1"
env_logger = "0.10.0"

[build-dependencies]
steel-gen = { path = "../steel-gen", version = "0.2.0" }

[features]
# TODO: Deprecate the modules feature flag, it no longer does anything
default = ["modules"]
modules = []
jit = ["dep:cranelift", "dep:cranelift-module", "dep:cranelift-jit"]
dynamic = []
profiling = []
web = ["dep:reqwest", "dep:url"]
sqlite = ["dep:rusqlite"]
unsafe-internals = []
anyhow = ["dep:anyhow"]
dylibs = ["dep:abi_stable", "dep:async-ffi"]
markdown = ["dep:termimad"]
smallvec = []
without-drop-protection = []
stacker = ["dep:stacker"]


[[bench]]
name = "my_benchmark"
harness = false
