[package]
name = "steel-parser"
version = "0.6.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["mattwparas <matthewparas2020@u.northwestern.edu>"]
repository = "https://github.com/mattwparas/steel"
description = "Parser for use within steel"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serde = { version = "1.0.152", features = ["derive", "rc"] }
serde_derive = "1.0.152"
num-bigint = { version = "0.4.0", features = ["serde"] }
lasso = { version = "0.7.2", features = ["multi-threaded", "serialize"] }
once_cell = "1.18.0"
pretty = "0.12.1"
fxhash = "0.2.1"
