name: Docker CI

on:
  push:
    branches:
      - master
  pull_request:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Authenticate to the Docker Hub
        if: ${{ github.event_name != 'pull_request' }}
        uses: docker/login-action@v3
        with:
          username: steelscheme
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      # disable push on merge requests
      - name: Test Build
        uses: docker/build-push-action@v6
        if: ${{ github.event_name == 'pull_request' }}
        with:
          push: false
          platforms: linux/amd64,linux/arm64
          tags: steelscheme/steel:latest

      - name: Build and push the docker image
        uses: docker/build-push-action@v6
        if: ${{ github.event_name != 'pull_request' }}
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: steelscheme/steel:latest
