name: Build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: cargo build --verbose
      - name: Run tests
        run: cd steel; cargo test --verbose --features colors_off
      - name: rust-tarpaulin
        uses: actions-rs/tarpaulin@v0.1.0
        with:
          command: test
          args: --all
