[package]
name = "steel"
version = "0.1.0"
authors = ["mattwparas <matthewparas2020@u.northwestern.edu>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
thiserror = "1.0.31"
im-rc = "15.1.0"
colored = "2.0.0"
# rand = "0.8.1"
codespan-reporting = "0.11.1"
# structopt = "0.3.21"
# unindent = "0.1.7"
logos = "0.12.0"
itertools = "0.10.3"
log = "0.4.11"
futures = "0.3.17"
# async-compat = "0.1.4"
serde_json = "1.0.81"
serde = { version = "1.0.137", features = ["derive", "rc"] }
serde_derive = "1.0.137"
bincode = "1.3.3"
# ahash = "0.6.3"
pretty = "0.11.3"
# Cranelift JIT
cranelift = { version = "0.84.0", optional = true }
cranelift-module = { version = "0.84.0", optional = true }
cranelift-jit = { version = "0.84.0", optional = true }
# typed-arena = "2.0.1"
# lazy_static = "1.4.0"
im-lists = "0.2.0"
quickscope = "0.2.0"
lasso = { version = "0.6.0", features = ["multi-threaded"] }
once_cell = "1.10.0"
fnv = "1.0.3"
dlopen = "0.1"
dlopen_derive = "0.1.4"

[dev-dependencies]
proptest = "1.0.0"
criterion = "0.3.5"
# steel = { path = ".", features = ["modules", "jit"] }
steel = { path = ".", features = ["modules"] }
env_logger = "0.9"

[features]
# this effectively enable the feature `no-color` of colored when testing with
# `cargo test --features colors_off`
colors_off = ["colored/no-color"]
modules = []
jit = []

[[bench]]
name = "my_benchmark"
harness = false
